"""Added user_id

Revision ID: d1f04ec919db
Revises: 9e18439e9cad
Create Date: 2026-09-24 18:14:30.572545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f04ec919db'
down_revision: Union[str, Sequence[str], None] = '9e18439e9cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'user_id')
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
